# Generated by Django 6.0.2 on 2026-03-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='general_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='security_mode',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='systemfield',
            name='related_display_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_for_fields', to='api.systemfield'),
        ),
        migrations.AddField(
            model_name='systemfield',
            name='related_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fields', to='api.systemtable'),
        ),
        migrations.AlterField(
            model_name='systemfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('relation', 'Relation')], max_length=20),
        ),
    ]
