# Generated by Django 4.2.29 on 2026-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_system_general_password_system_security_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_storage_mb',
            field=models.IntegerField(default=1024),
        ),
    ]
