# Generated by Django 4.2.29 on 2026-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plan_max_storage_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
