# Generated by Django 4.2.29 on 2026-03-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appsetting_user_role_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='api.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('system', 'user')},
            },
        ),
    ]
