# Generated by Django 4.2.29 on 2026-03-24 14:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_systemcollaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='securityaudit',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemcollaborator',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemfield',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemfieldoption',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemrecord',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemrecordvalue',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemrelationship',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemtable',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
