# Generated by Django 4.2.29 on 2026-03-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_repair_chat_schema'),
        ('chatbot', '0004_chatconversation_chatmessage_conversation'),
    ]

    operations = [
    ]
